/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class FormHome extends javax.swing.JPanel {

    /**
     * Creates new form FormHome
     */
    public FormHome() {
        initComponents();
        lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(FormHome.class.getResource("/Image/AnhQuanDoi/lang-bac-o-dau-hinh-anh-lang-bac-ho-3.jpg")).getScaledInstance(850, 500, java.awt.Image.SCALE_SMOOTH)));
        slideHeading();
        this.setSize(850, 500);
    }

    void slideHeading() {
        Timer t = new Timer(10, new ActionListener() {
            int x = 0;
            int y = 460;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (x < 850) {
                    x++;
                    lblHeading.setLocation(x, y);
                } else {
                    x = -440;
                    lblHeading.setLocation(x, y);
                }
            }
        });
        t.start();
    }

//    void slideShow() {
//        Timer t = new Timer(2000, new ActionListener() {
//            int x = 0;
//            String[] image = {"/Image/AnhQuanDoi/20267_Phong_Vang_mai_khuc_quan_hanh.jpg",
//                "/Image/AnhQuanDoi/quan-doi-anh-hung-ttxvn.jpg",
//                "/Image/AnhQuanDoi/86f669b2-1f49-414d-8301-b523b4a6df48.jpg"};
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (x == 2) {
//                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(FormHome.class.getResource(image[0])).getScaledInstance(850, 500, java.awt.Image.SCALE_SMOOTH)));
//                }
//                if (x == 5) {
//                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(FormHome.class.getResource(image[1])).getScaledInstance(850, 500, java.awt.Image.SCALE_SMOOTH)));
//                }
//                if (x == 8) {
//                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(FormHome.class.getResource(image[2])).getScaledInstance(850, 500, java.awt.Image.SCALE_SMOOTH)));
//                }
//                if (x == 11) {
//                    x = 1;
//                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(FormHome.class.getResource(image[0])).getScaledInstance(850, 500, java.awt.Image.SCALE_SMOOTH)));
//                }
//                x++;
//            }
//        });
//        t.start();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new JPanel.PanelBorder();
        lblHeading = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        panelBorder1.setPreferredSize(new java.awt.Dimension(860, 550));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 0, 0));
        lblHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/iconmonstr-star-filled-24.png"))); // NOI18N
        lblHeading.setText("NƯỚC CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM!");
        panelBorder1.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 440, 25));
        panelBorder1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblImage;
    private JPanel.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
