/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import EventMenu.EventMenu;
import EventMenu.EventMenuSelected;
import JavaClass.ModelMenu;
import static JavaClass.ModelMenu.MenuType.MENU;
import java.awt.Font;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.Icon;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Admin
 */
public class MenuItem extends javax.swing.JPanel {

    private boolean selected;
    private boolean over;

    public MenuItem(ModelMenu data) {
        initComponents();
        setOpaque(false);
        if (data.getType() == ModelMenu.MenuType.MENU) {
            lbIcon.setSize(27, 36);
            lbIcon.setIcon(data.toIcon());
            lbName.setText(data.getName());
        } else if (data.getType() == ModelMenu.MenuType.TITLE) {
            lbIcon.setText(data.getName());
            lbIcon.setFont(new Font("sansserif", 1, 12));
            lbName.setVisible(false);
        } else {
            lbName.setText(" ");
        }
    }


    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }

    public void setOver(boolean over) {
        this.over = over;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        if (selected || over) {
            Graphics2D g2 = (Graphics2D) grphcs;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            if (selected) {
                g2.setColor(new Color(20, 194, 15, 80));
            } else {
                g2.setColor(new Color(20, 194, 15, 40));
            }
            g2.fillRoundRect(5, 0, getWidth() - 10, getHeight(), 5, 5);
        }
        super.paintComponent(grphcs);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIcon = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 27, 36));

        lbName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 0, 0));
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName.setText("Name");
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 87, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
