/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Class.NhapQuanPhuc;
import DAO.NhapQuanPhucDAO;
import Helper.DateHelper;
import Helper.DialogHelper;
import Helper.JDBCHelper;
import JavaClass.Button;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhapQuanPhucJPanel extends javax.swing.JPanel {

    NhapQuanPhucDAO nhapDAO = new NhapQuanPhucDAO();
    private int indexTable = -1;

    /**
     * Creates new form NhapQuanPhucJPanel
     */
    public NhapQuanPhucJPanel() {
        initComponents();
        Edit();
        fillCombobox();
        fillTable();
    }

    void showForm(Component com
    ) {
        panelBorder1.removeAll();
        panelBorder1.setLayout(new BorderLayout());
        panelBorder1.add(com);
        panelBorder1.repaint();
        panelBorder1.revalidate();
    }

    void Edit() {
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        tblQuanPhuc.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblQuanPhuc.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblQuanPhuc.getColumnModel().getColumn(2).setPreferredWidth(135);

        button1.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button1.setFont(new Font("sansserif", 1, 12));
        button1.setText("Thêm");
        button2.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button2.setFont(new Font("sansserif", 1, 12));
        button2.setText("Sửa");
        button3.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button3.setFont(new Font("sansserif", 1, 12));
        button3.setText("Xóa");
        button4.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button4.setFont(new Font("sansserif", 1, 12));
        button4.setText("Mới");
        button5.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button5.setFont(new Font("sansserif", 1, 12));
        button5.setText("QP Đại Đội");
        button6.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button6.setFont(new Font("sansserif", 1, 12));
        button6.setText("Trở Lại");
        txtSoLuongNhap.setHint("SL Nhập");
    }

    void fillCombobox() {
        try {
            String sql = "Select TenQuanPhuc FROM QuanPhuc";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                cboQuanPhuc.addItem(rs.getString(1));
            }
            while (rs.next()) {
            }
        } catch (Exception e) {
        }
    }

    void Load() {
        txtSoLuongNhap.setText("");
        txtSoLuongNhap.requestFocus();
        indexTable = -1;
    }

    void insert() {
        NhapQuanPhuc model = new NhapQuanPhuc();
        String maQuanPhuc = "";
        try {
            String sql = "Select * FROM QuanPhuc";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString("TenQuanPhuc").equalsIgnoreCase(cboQuanPhuc.getSelectedItem().toString())) {
                    maQuanPhuc = rs.getString("MaQuanPhuc");
                    break;
                }
            }
            model.setMaQuanPhuc(maQuanPhuc);
            model.setNgayNhap(new java.sql.Date(DateHelper.now().getTime()));
            model.setSoLuong(Integer.parseInt(txtSoLuongNhap.getText()));
            try {
                nhapDAO.insert(model);
                fillTable();
                Load();
                DialogHelper.alert(this, "Nhập thành công!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblQuanPhuc.getModel();
        model.setRowCount(0);
        try {
            String sql = "EXEC sp_ThongKeSoLuongQuanPhucNhapVao";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                Object[] row = {rs.getString(1),
                    rs.getString(2),
                    rs.getInt(3)
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new JPanel.PanelBorder();
        scrollTable = new javax.swing.JScrollPane();
        tblQuanPhuc = new JavaClass.TableQuanPhuc();
        button1 = new JavaClass.Button();
        button2 = new JavaClass.Button();
        button3 = new JavaClass.Button();
        button4 = new JavaClass.Button();
        cboQuanPhuc = new JavaClass.Combobox();
        txtSoLuongNhap = new JavaClass.SearchText();
        button5 = new JavaClass.Button();
        button6 = new JavaClass.Button();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Quân Phục", "Tên Quân Phục", "Số Lượng Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTable.setViewportView(tblQuanPhuc);

        panelBorder1.add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 820, 320));

        button1.setText("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelBorder1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 90, -1));

        button2.setText("button2");
        panelBorder1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 90, -1));

        button3.setText("button3");
        panelBorder1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 90, -1));

        button4.setText("button4");
        panelBorder1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 90, -1));

        cboQuanPhuc.setLabeText("");
        panelBorder1.add(cboQuanPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 320, -1));
        panelBorder1.add(txtSoLuongNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 70, -1));

        button5.setText("button5");
        panelBorder1.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 90, -1));

        button6.setText("button6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        panelBorder1.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        showForm(new FormQuanPhuc());
    }//GEN-LAST:event_button6ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaClass.Button button1;
    private JavaClass.Button button2;
    private JavaClass.Button button3;
    private JavaClass.Button button4;
    private JavaClass.Button button5;
    private JavaClass.Button button6;
    private JavaClass.Combobox cboQuanPhuc;
    private JPanel.PanelBorder panelBorder1;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanPhuc tblQuanPhuc;
    private JavaClass.SearchText txtSoLuongNhap;
    // End of variables declaration//GEN-END:variables
}
