/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Class.NhapQuanPhuc;
import Helper.JDBCHelper;
import JavaClass.Button;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.BorderFactory;

/**
 *
 * @author Admin
 */
public class NhapQuanPhucJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhapQuanPhucJPanel
     */
    public NhapQuanPhucJPanel() {
        initComponents();
        Edit();
        fillCombobox();
    }

    void Edit() {
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        tblQuanPhuc.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblQuanPhuc.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblQuanPhuc.getColumnModel().getColumn(2).setPreferredWidth(135);

        button1.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button1.setFont(new Font("sansserif", 1, 12));
        button1.setText("Thêm");
        button2.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button2.setFont(new Font("sansserif", 1, 12));
        button2.setText("Sửa");
        button3.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button3.setFont(new Font("sansserif", 1, 12));
        button3.setText("Xóa");
        button4.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button4.setFont(new Font("sansserif", 1, 12));
        button4.setText("Mới");
    }

    void fillCombobox() {
        try {
            String sql = "Select TenQuanPhuc FROM QuanPhuc";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                cboQuanPhuc.addItem(rs.getString(1));
            }
            while (rs.next()) {
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new JPanel.PanelBorder();
        scrollTable = new javax.swing.JScrollPane();
        tblQuanPhuc = new JavaClass.TableQuanPhuc();
        button1 = new JavaClass.Button();
        button2 = new JavaClass.Button();
        button3 = new JavaClass.Button();
        button4 = new JavaClass.Button();
        cboQuanPhuc = new JavaClass.Combobox();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã Quân Phục", "Tên Quân Phục", "Số Lượng Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTable.setViewportView(tblQuanPhuc);

        panelBorder1.add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 257, 826, 230));

        button1.setText("button1");
        panelBorder1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 80, -1));

        button2.setText("button2");
        panelBorder1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 80, -1));

        button3.setText("button3");
        panelBorder1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 80, -1));

        button4.setText("button4");
        panelBorder1.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 80, -1));

        cboQuanPhuc.setLabeText("");
        panelBorder1.add(cboQuanPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
void insert() {
        NhapQuanPhuc model = new NhapQuanPhuc();
        model.setMaQuanPhuc(TOOL_TIP_TEXT_KEY);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaClass.Button button1;
    private JavaClass.Button button2;
    private JavaClass.Button button3;
    private JavaClass.Button button4;
    private JavaClass.Combobox cboQuanPhuc;
    private JPanel.PanelBorder panelBorder1;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanPhuc tblQuanPhuc;
    // End of variables declaration//GEN-END:variables
}
