/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Class.QuanPhucDaiDoi;
import DAO.QuanPhucDaiDoiDAO;
import Helper.DialogHelper;
import Helper.JDBCHelper;
import JavaClass.Button;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanPhucDaiDoiJPanel extends javax.swing.JPanel {

    QuanPhucDaiDoiDAO qpddDAO = new QuanPhucDaiDoiDAO();
    private int indexTable = -1, indexCBO = -1;

    /**
     * Creates new form QuanTrangDaiDoiJPanel
     */
    public QuanPhucDaiDoiJPanel() {
        initComponents();
        addItem();
        fillTable();
        Edit();
        fillCombobox();
    }

    void Edit() {
        button1.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button1.setFont(new Font("sansserif", 1, 12));
        button1.setText("Trở lại");
        button2.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button2.setFont(new Font("sansserif", 1, 12));
        button2.setText("Thêm");
        button3.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button3.setFont(new Font("sansserif", 1, 12));
        button3.setText("Sửa");
        txtSoLuongNhap.setHint("Số lượng");
    }

    void addItem() {
        QuanPhucDaiDoi model = new QuanPhucDaiDoi();
        try {
            String sql = "SELECT QuanPhuc.MaQuanPhuc,QuanPhuc.TenQuanPhuc FROM QuanPhuc\n"
                    + "EXCEPT\n"
                    + "SELECT QuanPhuc.MaQuanPhuc,QuanPhuc.TenQuanPhuc FROM QuanPhuc LEFT JOIN QuanPhucDaiDoi\n"
                    + "ON QuanPhuc.MaQuanPhuc = QuanPhucDaiDoi.MaQuanPhuc  WHERE QuanPhucDaiDoi.MaDaiDoi = '" + DaiDoiJPanel.maDaiDoi + "'";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                model.setMaDaiDoi(DaiDoiJPanel.maDaiDoi);
                model.setMaQuanPhuc(rs.getString("MaQuanPhuc"));
                model.setSoLuong(0);
                qpddDAO.insert(model);
            }
        } catch (Exception e) {
        }
    }

    void fillCombobox() {
        try {
            String sql = "EXEC sp_ThongKeSoLuongQuanPhucNhapVao";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                cboQuanPhuc.addItem(rs.getString(2));
            }
        } catch (Exception e) {
        }
    }

    void fillTable() {
        lblDaiDoi.setText("Đại Đội: " + DaiDoiJPanel.tenDaiDoi);
        DefaultTableModel model = (DefaultTableModel) tblQuanPhuc.getModel();
        try {
            String sql = "Select QuanPhucDaiDoi.MaQuanPhuc,\n"
                    + "QuanPhuc.TenQuanPhuc,QuanPhucDaiDoi.SoLuong\n"
                    + "FROM QuanPhucDaiDoi INNER JOIN QuanPhuc\n"
                    + "On QuanPhucDaiDoi.MaQuanPhuc = QuanPhuc.MaQuanPhuc \n"
                    + "WHERE QuanPhucDaiDoi.MaDaiDoi = '" + DaiDoiJPanel.maDaiDoi + "'";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                Object[] row = {DaiDoiJPanel.maDaiDoi, rs.getString(1), rs.getString(2), rs.getInt(3)};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new JPanel.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanPhuc = new JavaClass.TableQuanPhuc();
        button1 = new JavaClass.Button();
        lblDaiDoi = new javax.swing.JLabel();
        txtSoLuongCo = new JavaClass.SearchText();
        txtSoLuongNhap = new JavaClass.SearchText();
        button2 = new JavaClass.Button();
        button3 = new JavaClass.Button();
        jLabel1 = new javax.swing.JLabel();
        cboQuanPhuc = new JavaClass.Combobox();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Đại Đội", "Mã Quân Phuc", "Tên Quân Phục", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuanPhuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanPhucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanPhuc);

        panelBorder1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 820, 330));

        button1.setText("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelBorder1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, -1));

        lblDaiDoi.setText("Đại Đội: ");
        panelBorder1.add(lblDaiDoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtSoLuongCo.setEditable(false);
        panelBorder1.add(txtSoLuongCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 70, -1));
        panelBorder1.add(txtSoLuongNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 70, -1));

        button2.setText("button2");
        panelBorder1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 80, -1));

        button3.setText("button3");
        panelBorder1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 80, -1));

        jLabel1.setText("Có:");
        panelBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        cboQuanPhuc.setLabeText("");
        cboQuanPhuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboQuanPhucItemStateChanged(evt);
            }
        });
        panelBorder1.add(cboQuanPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    void showForm(Component com
    ) {
        panelBorder1.removeAll();
        panelBorder1.setLayout(new BorderLayout());
        panelBorder1.add(com);
        panelBorder1.repaint();
        panelBorder1.revalidate();
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        showForm(new DaiDoiJPanel());
    }//GEN-LAST:event_button1ActionPerformed

    private void tblQuanPhucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanPhucMouseClicked
        // TODO add your handling code here:
        indexTable = tblQuanPhuc.getSelectedRow();
        try {
            if (indexTable == -1) {
                DialogHelper.alert(this, "Vui lòng chọn quân phục cần thêm!");
            } else {

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblQuanPhucMouseClicked

    private void cboQuanPhucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboQuanPhucItemStateChanged
        // TODO add your handling code here:
//        if (indexCBO == -1) {
//            indexCBO = cboQuanPhuc.getSelectedIndex();
//        } else {
//            String maQuanPhuc = "";
//            try {
//                String sql = "Select * FROM QuanPhuc";
//                ResultSet rs = JDBCHelper.executeQuery(sql);
//                while (rs.next()) {
//                    if (cboQuanPhuc.setSelectedIndex(indexCBO).toString().equalsIgnoreCase(rs.getString("TenQuanPhuc"))) {
//                        maQuanPhuc = rs.getString("MaQuanPhuc");
//                        break;
//                    }
//                }
//                try {
//                    String sqlLoad = "SELECT \n"
//                            + "SUM(NhapQuanPhuc.SoLuong) SoLuong\n"
//                            + "FROM NhapQuanPhuc INNER JOIN QuanPhuc\n"
//                            + "ON NhapQuanPhuc.MaQuanPhuc = QuanPhuc.MaQuanPhuc\n"
//                            + "WHERE QuanPhuc.MaQuanPhuc = '" + maQuanPhuc + "' \n"
//                            + "GROUP BY NhapQuanPhuc.MaQuanPhuc,QuanPhuc.TenQuanPhuc";
//                    ResultSet rst = JDBCHelper.executeQuery(sql);
//                    while (rs.next()) {
//                        txtSoLuongCo.setText(String.valueOf(rst.getInt(1)));
//                    }
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_cboQuanPhucItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaClass.Button button1;
    private JavaClass.Button button2;
    private JavaClass.Button button3;
    private JavaClass.Combobox cboQuanPhuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDaiDoi;
    private JPanel.PanelBorder panelBorder1;
    private JavaClass.TableQuanPhuc tblQuanPhuc;
    private JavaClass.SearchText txtSoLuongCo;
    private JavaClass.SearchText txtSoLuongNhap;
    // End of variables declaration//GEN-END:variables
}
