/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Helper.JDBCHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKeQuanNhanJPanel extends javax.swing.JPanel {

    private int indexCBO = -1;

    /**
     * Creates new form ThongKeQuanNhan
     */
    public ThongKeQuanNhanJPanel() {
        initComponents();
    }

    void fillTable(int year) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblQuanNhan.getModel();
        model.setRowCount(0);
        ResultSet rs = null;
        try {
            String sql = "EXEC sp_ThongKeQuanNhan '" + year + "'";
            rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("Nam"),
                    rs.getString("DonVi"),
                    rs.getInt("SoLuong"),};
                model.addRow(row);
            }
        } finally {
            rs.getStatement().getConnection().close();
        }
    }

    void fillComboboxNam() {
        try {
            String sql = "SELECT YEAR(NhapNgu) Nam FROM QuanNhan GROUP BY YEAR(NhapNgu)";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                cboNam.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanNhan = new JavaClass.TableQuanNhan();
        jLabel1 = new javax.swing.JLabel();
        cboNam = new JavaClass.Combobox();

        setBackground(new java.awt.Color(255, 255, 255));

        tblQuanNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Năm", "Đại Đội", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQuanNhan);

        jLabel1.setText("THỐNG KÊ QUÂN NHÂN");

        cboNam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2021", "2022", "2023" }));
        cboNam.setLabeText("");
        cboNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNamItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNamItemStateChanged
        // TODO add your handling code here:
        if (indexCBO == -1) {
            indexCBO = cboNam.getSelectedIndex();
        } else {
            indexCBO = cboNam.getSelectedIndex();
            try {
                fillTable(Integer.parseInt(cboNam.getItemAt(indexCBO).toString()));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cboNamItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaClass.Combobox cboNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private JavaClass.TableQuanNhan tblQuanNhan;
    // End of variables declaration//GEN-END:variables
}
