/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Class.QuanPhuc;
import Helper.JDBCHelper;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKeQuanPhucConLaiJPanel extends javax.swing.JPanel {

    List<QuanPhuc> ListQP = new ArrayList<>();

    /**
     * Creates new form QuanPhucConLai
     */
    public ThongKeQuanPhucConLaiJPanel() {
        initComponents();
        fillTableQuanPhucDaPhat();
        init();
    }

    void init() {
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        tblQuanPhuc.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblQuanPhuc.getColumnModel().getColumn(1).setPreferredWidth(130);
        tblQuanPhuc.getColumnModel().getColumn(2).setPreferredWidth(80);
        fillTableQuanPhucDaPhat();
        tblQuanPhuc.setLocation(10, 100);
    }

    void fillTableQuanPhucDaPhat() {
        DefaultTableModel model = (DefaultTableModel) tblQuanPhuc.getModel();
        model.setRowCount(0);
        try {
            String sql = "Select * FROM QuanPhuc";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                String sqlLoadData = "EXEC sp_ThongKeQuanPhucConLai '" + rs.getString("MaQuanPhuc") + "'";
                ResultSet rst = JDBCHelper.executeQuery(sqlLoadData);
                while (rst.next()) {
                    Object[] row = {rs.getString("MaQuanPhuc"), rs.getString("TenQuanPhuc"), rst.getInt(1)};
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder2 = new JPanel.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        tblQuanPhuc = new JavaClass.TableQuanPhuc();

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder2.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("QUÂN PHỤC");

        scrollTable.setBorder(null);

        tblQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Quân Phục", "Tên Quân Phục", "Số Lượng Còn"
            }
        ));
        scrollTable.setViewportView(tblQuanPhuc);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 747, Short.MAX_VALUE))
                    .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private JPanel.PanelBorder panelBorder2;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanPhuc tblQuanPhuc;
    // End of variables declaration//GEN-END:variables
}
