/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Helper.DialogHelper;
import Helper.JDBCHelper;
import JavaClass.Button;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FormQuanPhuc extends javax.swing.JPanel {

    /**
     * Creates new form FormQuanPhuc
     */
    public FormQuanPhuc() {
        initComponents();
        editForm();
        fillTableQuanPhuc();
    }
    
    void editForm() {
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        tblQuanPhuc.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblQuanPhuc.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblQuanPhuc.getColumnModel().getColumn(2).setPreferredWidth(135);
        lblImage.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        button1.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button1.setFont(new Font("sansserif", 1, 12));
        button1.setText("Thêm");
        button2.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button2.setFont(new Font("sansserif", 1, 12));
        button2.setText("Sửa");
        button3.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button3.setFont(new Font("sansserif", 1, 12));
        button3.setText("Xóa");
        button4.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button4.setFont(new Font("sansserif", 1, 12));
        button4.setText("Mới");
        txtMaQP.setHint("Mã quân phục");
        txtTenQuanPhuc.setHint("Tên quân phục");
    }
    
    void fillTableQuanPhuc() {
        DefaultTableModel model = (DefaultTableModel) tblQuanPhuc.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT * FROM QuanPhuc";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                char[] charArrayName = rs.getString("TenQuanPhuc").toCharArray();
                boolean foundSpaceName = true;
                //sử dụng vòng lặp for để duyệt các phần tử trong charArray
                for (int i = 0; i < charArrayName.length; i++) {
                    // nếu phần tử trong mảng là một chữ cái
                    if (Character.isLetter(charArrayName[i])) {
                        // kiểm tra khoảng trắng có trước chữ cái
                        if (foundSpaceName) {
                            //đổi chữ cái thành chữ in hoa bằng phương thức toUpperCase()
                            charArrayName[i] = Character.toUpperCase(charArrayName[i]);
                            foundSpaceName = false;
                        }
                    } else {
                        foundSpaceName = true;
                    }
                }
                String fullName = String.valueOf(charArrayName);
                Object[] row = new Object[]{rs.getString("MaQuanPhuc").toUpperCase(),
                    fullName,
                    rs.getInt("ThoiGianCap"),
                rs.getString("HinhAnh")
            };
            model.addRow(row);
        }
    }
    catch (SQLException e

    
        ) {
            DialogHelper.alert(this, "Lỗi truy vấn quân phục! " + e);
        
    }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        tblQuanPhuc = new JavaClass.TableQuanPhuc();
        jLabel2 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        txtMaQP = new JavaClass.SearchText();
        txtTenQuanPhuc = new JavaClass.SearchText();
        button1 = new JavaClass.Button();
        button2 = new JavaClass.Button();
        button3 = new JavaClass.Button();
        button4 = new JavaClass.Button();
        cboNam = new JavaClass.Combobox();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã QP", "Tên Quân Phục", "Thời Gian Cấp (Năm)", "Hình Ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTable.setViewportView(tblQuanPhuc);

        add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, 547, 442));

        jLabel2.setText("QUẢN LÝ QUÂN PHỤC");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 45, 140, 183));
        add(txtMaQP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 189, -1));
        add(txtTenQuanPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 189, -1));

        button1.setText("button1");
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 86, -1));

        button2.setText("button2");
        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 85, -1));

        button3.setText("button3");
        add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 86, -1));

        button4.setText("button4");
        add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 85, -1));

        cboNam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cboNam.setLabeText("");
        add(cboNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 190, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaClass.Button button1;
    private JavaClass.Button button2;
    private JavaClass.Button button3;
    private JavaClass.Button button4;
    private JavaClass.Combobox cboNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanPhuc tblQuanPhuc;
    private JavaClass.SearchText txtMaQP;
    private JavaClass.SearchText txtTenQuanPhuc;
    // End of variables declaration//GEN-END:variables
}
