/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Helper.*;
import JavaClass.Model_Card;
import JavaClass.StatusType;
import JavaClass.TableQuanNhan;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javafx.scene.control.ScrollBar;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Admin
 */
public class FormThongKe extends javax.swing.JPanel {

    /**
     * Creates new form FormHome
     */
    public FormThongKe() {
        initComponents();
        addItem();
    }

    public void setSelectedIndex(int index) {
        if (index == 0) {
            setForm(new ThongKeQuanPhucDaPhatJPanel());
        } else if (index == 1) {
            setForm(new ThongKeQuanPhucConLaiJPanel());
        } else {

        }
    }

    void addItem() {
        card4.setData(new Model_Card(new ImageIcon(getClass().getResource("/Image/Icon/User.png")), "Quân Phục Đã Phát", "Số Lượng:"));
        card5.setData(new Model_Card(new ImageIcon(getClass().getResource("/Image/Icon/iconmonstr-clothing-3-24.png")), "Quân Phục Còn Lại", "Số Lượng:"));
        card6.setData(new Model_Card(new ImageIcon(getClass().getResource("/Image/Icon/User.png")), "Quân Nhân", "Số Lượng:"));
//add tblQuanNhan
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        setSizeTable();
        fillTableQuanNhan();
    }

    void setSizeTable() {
        tblQuanNhan.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblQuanNhan.getColumnModel().getColumn(1).setPreferredWidth(130);
        tblQuanNhan.getColumnModel().getColumn(2).setPreferredWidth(80);
    }

    void fillTableQuanNhan() {
        DefaultTableModel model = (DefaultTableModel) tblQuanNhan.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT * FROM QuanNhan";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                char[] charArrayName = rs.getString("HoTen").toCharArray();
                boolean foundSpaceName = true;
                //sử dụng vòng lặp for để duyệt các phần tử trong charArray
                for (int i = 0; i < charArrayName.length; i++) {
                    // nếu phần tử trong mảng là một chữ cái
                    if (Character.isLetter(charArrayName[i])) {
                        // kiểm tra khoảng trắng có trước chữ cái
                        if (foundSpaceName) {
                            //đổi chữ cái thành chữ in hoa bằng phương thức toUpperCase()
                            charArrayName[i] = Character.toUpperCase(charArrayName[i]);
                            foundSpaceName = false;
                        }
                    } else {
                        foundSpaceName = true;
                    }
                }
                String fullName = String.valueOf(charArrayName);
                StatusType type;
                String gt = "";
                if (rs.getBoolean("GioiTinh")) {
                    gt = "Nam";
                } else {
                    gt = "Nữ";
                }
                if (rs.getBoolean("TrangThaiQuanPhuc")) {
                    type = StatusType.APPROVED;
                } else {
                    type = StatusType.PENDING;
                }
                Object[] row = new Object[]{rs.getString("MaQN").toUpperCase(),
                    fullName,
                    rs.getString("ChucVu"),
                    rs.getString("DonVi"),
                    rs.getDate("NgaySinh"),
                    gt,
                    rs.getDate("NhapNgu"),
                    type};
                tblQuanNhan.addRow(row);
            }
        } catch (SQLException e) {
            DialogHelper.alert(this, "Lỗi truy vấn quân nhân! " + e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card4 = new JPanel.Card();
        card5 = new JPanel.Card();
        card6 = new JPanel.Card();
        panelBorder2 = new JPanel.PanelBorder();
        scrollTable = new javax.swing.JScrollPane();
        tblQuanNhan = new JavaClass.TableQuanNhan();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(688, 500));

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 20, 10));

        card4.setColor1(new java.awt.Color(204, 255, 255));
        card4.setColor2(new java.awt.Color(0, 153, 204));
        card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card4MouseClicked(evt);
            }
        });
        jPanel1.add(card4);

        card5.setColor1(new java.awt.Color(255, 153, 255));
        card5.setColor2(new java.awt.Color(204, 0, 204));
        card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card5MouseClicked(evt);
            }
        });
        jPanel1.add(card5);

        card6.setColor1(new java.awt.Color(255, 153, 153));
        card6.setColor2(new java.awt.Color(255, 0, 0));
        card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card6MouseClicked(evt);
            }
        });
        jPanel1.add(card6);

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        scrollTable.setBorder(null);
        scrollTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblQuanNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã QN", "Họ & Tên", "Cấp Bậc", "ĐV", "Ngày Sinh", "GT", "Nhập Ngũ", "Nhận QP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuanNhan.setOpaque(false);
        scrollTable.setViewportView(tblQuanNhan);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("QUÂN NHÂN");

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTable)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    void setForm(JComponent com) {
        panelBorder2.removeAll();
        panelBorder2.add(com);
        panelBorder2.repaint();
        panelBorder2.revalidate();
    }
    private void card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card4MouseClicked
        // TODO add your handling code here:
        panelBorder2.removeAll();
        panelBorder2.setLayout(new BorderLayout());
        panelBorder2.add(new ThongKeQuanPhucDaPhatJPanel());
        panelBorder2.repaint();
        panelBorder2.revalidate();
    }//GEN-LAST:event_card4MouseClicked

    private void card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card6MouseClicked
        // TODO add your handling code here:
        panelBorder2.removeAll();
        panelBorder2.setLayout(new BorderLayout());
        panelBorder2.add(new FormQuanNhan());
        panelBorder2.repaint();
        panelBorder2.revalidate();
    }//GEN-LAST:event_card6MouseClicked

    private void card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card5MouseClicked
        // TODO add your handling code here:
        panelBorder2.removeAll();
        panelBorder2.setLayout(new BorderLayout());
        panelBorder2.add(new ThongKeQuanPhucConLaiJPanel());
        panelBorder2.repaint();
        panelBorder2.revalidate();
    }//GEN-LAST:event_card5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel.Card card4;
    private JPanel.Card card5;
    private JPanel.Card card6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private JPanel.PanelBorder panelBorder2;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanNhan tblQuanNhan;
    // End of variables declaration//GEN-END:variables
}
