/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Class.QuanNhan;
import DAO.QuanNhanDAO;
import Helper.DialogHelper;
import Helper.JDBCHelper;
import JavaClass.Button;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SizeQuanPhuc extends javax.swing.JPanel {

    QuanNhanDAO qnDAO = new QuanNhanDAO();
    List<QuanNhan> List = new ArrayList<>();

    /**
     * Creates new form PhatQuanPhuc
     */
    public SizeQuanPhuc() {
        initComponents();
        setTable();
        fillTableQuanNhan();
        Edit();
    }

    void Edit() {
        txtCao.setHint("Dài");
        txtRong.setHint("Rộng");
        txtCanNang.setHint("Cân nặng");
    }

    void showSize() {
        DialogHelper.alert(this, "<html><strong style='font-size:20px'>Chiều dài quân phục:</strong>\n"
                + "<html><strong style='color:red;'>Chiều Cao (cm)| Chiều Rộng (cm)| Cân Nặng (kg) |   Size   </strong></html>\n"
                + "          62                        37                       40-47                   S     \n"
                + "          66                        40                       48-57                   M     \n"
                + "          69                        43                       58-67                   L     \n"
                + "          72                        46                       68-77                   XL     \n"
                + "          74                        48                       78-85                   XXL    \n"
                + "          76                        50                       86-94                   XXXL    \n"
        );
    }

    void setTable() {
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        tblSizeQuanPhuc.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblSizeQuanPhuc.getColumnModel().getColumn(1).setPreferredWidth(120);
        button1.setStyle(Button.ButtonStyle.DESTRUCTIVE);
        button1.setFont(new Font("sansserif", 1, 12));
        button1.setText("Trở lại");
    }

    void fillTableQuanNhan() {
        DefaultTableModel model = (DefaultTableModel) tblSizeQuanPhuc.getModel();
        model.setRowCount(0);
        try {
            String sql = "select SizeQuanPhuc.MaDinhDanh,QuanNhan.HoTen,SizeQuanPhuc.SizeQuanPhuc,SizeQuanPhuc.SizeGiay,SizeQuanPhuc.SizeMu\n"
                    + "from SizeQuanPhuc inner join QuanNhan on SizeQuanPhuc.MaDinhDanh = QuanNhan.MaDinhDanh";
            ResultSet rs = JDBCHelper.executeQuery(sql);
            while (rs.next()) {
                Object[] row = new Object[]{rs.getString(1),
                    rs.getString(2),
                    rs.getInt(3),
                    rs.getInt(4),
                    rs.getInt(5)};
                model.addRow(row);
            }
        } catch (SQLException e) {
            DialogHelper.alert(this, "Lỗi truy vấn quân nhân! " + e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new JPanel.PanelBorder();
        button1 = new JavaClass.Button();
        scrollTable = new javax.swing.JScrollPane();
        tblSizeQuanPhuc = new JavaClass.TableQuanPhuc();
        lblQuanNhan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCao = new JavaClass.SearchText();
        txtRong = new JavaClass.SearchText();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCanNang = new JavaClass.SearchText();
        cboSizeGiay = new JavaClass.Combobox();
        cboSizeMu = new JavaClass.Combobox();

        setBackground(new java.awt.Color(255, 255, 255));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setPreferredSize(new java.awt.Dimension(850, 500));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setText("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelBorder1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 90, -1));

        tblSizeQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Quân Nhân", "Tên Quân Nhân", "Size Quân Phục", "Size Giày", "Size Mũ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTable.setViewportView(tblSizeQuanPhuc);

        panelBorder1.add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 830, 300));

        lblQuanNhan.setText("Quân Nhân:");
        panelBorder1.add(lblQuanNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jLabel1.setText("Size Quân Phục:");
        panelBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel2.setText("Size Giày:");
        panelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel3.setText("Size Mũ:");
        panelBorder1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        panelBorder1.add(txtCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 60, -1));
        panelBorder1.add(txtRong, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 60, -1));

        jLabel4.setText("X");
        panelBorder1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Numbered list.png"))); // NOI18N
        jLabel5.setText("Size");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelBorder1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jLabel6.setText("X");
        panelBorder1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 40, -1, -1));
        panelBorder1.add(txtCanNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 60, -1));

        cboSizeGiay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45" }));
        cboSizeGiay.setLabeText("");
        panelBorder1.add(cboSizeGiay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 220, 40));

        cboSizeMu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "54", "55", "56", "57", "58", "59", "60", "61", "62" }));
        cboSizeMu.setLabeText("");
        panelBorder1.add(cboSizeMu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
void showForm(Component com) {
        panelBorder1.removeAll();
        panelBorder1.setLayout(new BorderLayout());
        panelBorder1.add(com);
        panelBorder1.repaint();
        panelBorder1.revalidate();
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        showForm(new FormQuanNhan());
    }//GEN-LAST:event_button1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        showSize();
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaClass.Button button1;
    private JavaClass.Combobox cboSizeGiay;
    private JavaClass.Combobox cboSizeMu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblQuanNhan;
    private JPanel.PanelBorder panelBorder1;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanPhuc tblSizeQuanPhuc;
    private JavaClass.SearchText txtCanNang;
    private JavaClass.SearchText txtCao;
    private JavaClass.SearchText txtRong;
    // End of variables declaration//GEN-END:variables
}
