/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Class.QuanPhuc;
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKeQuanPhucDaPhatJPanel extends javax.swing.JPanel {

    List<QuanPhuc> ListQP = new ArrayList<>();

    /**
     * Creates new form FormQuanPhucDaPat
     */
    public ThongKeQuanPhucDaPhatJPanel() {
        initComponents();
        init();
        fillTableQuanPhucDaPhat();
    }

    void init() {
        scrollTable.setVerticalScrollBar(new JavaClass.ScrollBar());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        tblQuanPhuc.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblQuanPhuc.getColumnModel().getColumn(1).setPreferredWidth(130);
        tblQuanPhuc.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblQuanPhuc.setLocation(10, 100);
    }

    void fillTableQuanPhucDaPhat() {
        ListQP.add(new QuanPhuc(1, 142, "Áo Ba Lỗ"));
        ListQP.add(new QuanPhuc(2, 51, "Nội Vụ"));
        ListQP.add(new QuanPhuc(3, 66, "Ak47"));
        ListQP.add(new QuanPhuc(4, 99, "Mũ Cối"));
        ListQP.add(new QuanPhuc(5, 251, "Quân Phục"));
        ListQP.add(new QuanPhuc(6, 83, "Dây Nịt"));
        for (QuanPhuc qp : ListQP) {
            Object[] row = new Object[]{qp.getMaQP(), qp.getTenQP(), qp.getSoLuong()};
            tblQuanPhuc.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder2 = new JPanel.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        tblQuanPhuc = new JavaClass.TableQuanPhuc();

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder2.setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("QUÂN PHỤC");

        scrollTable.setBorder(null);

        tblQuanPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Quân Phục", "Tên Quân Phục", "Số Lượng Phát"
            }
        ));
        scrollTable.setViewportView(tblQuanPhuc);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private JPanel.PanelBorder panelBorder2;
    private javax.swing.JScrollPane scrollTable;
    private JavaClass.TableQuanPhuc tblQuanPhuc;
    // End of variables declaration//GEN-END:variables
}
